### ISSUE TITLE
Somehow console script is not available

### ISSUE THREAD

**Issue by kootenpv** [jgehrcke/python-cmdline-bootstrap#2]
Sorry to write it here, but I don't know what to do. 

My package [yagmail](https://github.com/kootenpv/yagmail/) is not getting a console_scripts entry point, even though with the exception of **version**, I completely followed your style, it seemed to all work out. 

Could you see what is wrong with it? Code works under Python 2 and 3. 

Also, could it be that python setup.py bdist_wininst gives an error after defining such an entry point on a Mac?

**Comment by jgehrcke** [comment]
Did you resolve the issue you were observing?

**Comment by kootenpv** [comment]
Yea, I assume it was something silly, perhaps __init__ related or having to upgrade with pip install -U or something.
